### ISSUE TITLE
myModes share

### ISSUE THREAD

**Issue by gazsy** [jhotmann/tasker-phone-modes#9]
Hello,

For a few weeks now, I've been looking for a profile where the tasker change the home/work/outside modes. I found yours.
I tried to create mine "myModes" some days ago, but I think I did something wrong, due to it did not change the "modes" automatic. After I deleted that.

Is it possible to share your "myModes" profile?

Thank you in advance for your reply

**Comment by jhotmann** [comment]
First create some config files and put them in `/sdcard/Tasker/ModeConfigs`

Examples:

`home.json`

```json
{
  "type": 1,
  "priority": 10,
  "volume_notification": 3,
  "volume_media": 7,
  "dnd": "all",
  "wifiOn": true,
  "bluetoothOn": true,
  "screenRotationOn": false,
  "displayTimeout": 1,
  "displayBrightness": "auto",
  "extraDimOn": false,
  "hapticFeedbackOn": true
}
```

`work.json`

```json
{
  "type": 1,
  "priority": 11,
  "volume_notification": 0,
  "volume_media": 0,
  "dnd": "all",
  "wifiOn": true,
  "screenRotationOn": false,
  "displayTimeout": 1,
  "displayBrightness": "auto",
  "extraDimOn": false,
  "hapticFeedbackOn": true,
  "enter": {
    "profilesToEnable": ["Work App Hider"]
  },
  "exit": {
    "profilesToDisable": ["Work App Hider"]
  }
}
```

`rotate.json`

```json
{
  "type": 2,
  "priority": 80,
  "screenRotationOn": true
}
```

Then import the project via XML or Taskernet, make sure to run the setup task to enable the correct profiles and set variables.

Then create some profiles to activate the contexts. For example wifi connected to your home wifi. Enter task call `AddToContext` task with `home` as parameter 1. Add an exit task that calls `RemoveFromContext` task with `home` as parameter 1.

Do similar for work (I use Wifi near since I don't connect to my work's wifi network).

With `rotate.json` as an example, I have a profile that is triggered by any apps I want to have auto-rotatation enabled, and the enter and exit tasks use `rotate` as parameter 1. Once you add these profiles you should start seeing toast messages of your context changing and can test and expand to more situations.

One thing to note is that if you add/edit config files you will need to run the `ReadConfigFiles` task for those changes to be reflected because the config file data is cached in a Tasker variable to speed things up.

Let me know if that works for you or you have any other questions!

**Comment by jhotmann** [comment]
No response, so closing
